version: '3'
services:
  mongodb:
    image: "mongo:3.4"
    ports:
      - "27017:27017"
    volumes:
      - "/home/mymongo:/data/db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}